### ISSUE TITLE
Review: Edit Inventory Notification

### ISSUE THREAD

**Issue by skimura1** [Runtime-Terrorz/HOME-Project-v2#27]
## Overview

The focus for this code review will be centered around the EditInventory page, Notification component.
    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-27](https://github.com/Runtime-Terrorz/HOME-Project-v2/tree/review-27)

## Files to review

* [EditInventory](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/pages/EditInventory.jsx)
* [Notification](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/components/Notification.jsx)

## Checklists

* [Architecture](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/checklists/js-checklist.md)
* [React](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/checklists/testing-checklist.md)

## Due date

October 15, 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by tonylong1314520** [comment]
EditInventory
DE-05: Change location from textfield to selectfield
TA-01: Need isDisplayed() test

Notification
DE-05 L33/L37: Change comments about stuff to inventories
TA-01: Need isDisplayed() test

**Comment by darneii** [comment]
EditInventory.jsx

> TA-01: isDisplayed() test


Notification.jsx

> L33, 37 DE-05: Change Stuff to Inventory
> TA-01: isDisplayed() test

No ESLint errors

**Comment by micahima** [comment]
Notification.jsx
- DE-05 L33,37: change Stuff to Inventory
- JS-01 L20: change notitem  to notItem
