### ISSUE TITLE
Review:  Dispense & Inventory

### ISSUE THREAD

**Issue by skimura1** [Runtime-Terrorz/HOME-Project-v2#47]
## Overview

The focus for this code review will be centered around the Inventory and DispenseInventory page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-47](https://github.com/Runtime-Terrorz/HOME-Project-v2/tree/review-47)

## Files to review

* [DispenseInventory.jsx](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/pages/DispenseInventory.jsx)
* [Inventory.jsx](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/pages/Inventory.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

November 2nd, 12:00PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ruizaj** [comment]
DispenseInventory.jsx
- JS-01 L73: placeholder should be "notes"
- DE-06 L36, 78: Should make the styles into css classes
- DE-06 L33: put container centered in the front for readability.

Inventory.jsx
- DE-05 L10-54: Alot of unnecessary comments that can be summed to be more readable.
- DE-06 L72,80,94: Should maintain style into css class.
- JS-01 L94: className should be "listContainer"
- JS-01 38/86, 41/87: Maybe have better names for the filter states.

**Comment by cammoore** [comment]
## DispenseInventory.jsx

Is doc a good variable name?
https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/d916654b6440648e7074a91887e4b902f5a876f4/app/imports/ui/pages/DispenseInventory.jsx#L18

## Inventory.jsx

JSDoc comments.

Is filtering/sorting cumulative with the search bar?
https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/d916654b6440648e7074a91887e4b902f5a876f4/app/imports/ui/pages/Inventory.jsx#L52-L56

**Comment by skimura1** [comment]
Inventory.jsx
DE-05 L44: Stray comment
JS-01: L18: change handleChange to handleFilter to follow name scheme
Possible bug. Can filter or search. However, can’t filter and search.

DispenseInventory.jsx
JS-01 variable name “quantity” can be confusing. Maybe, dispenseQuantity or inventoryQuantity
Maybe throw error when the user types in more dispenseQuantity than the inventoryQuantity

**Comment by tonylong1314520** [comment]
DispenseInventory.jsx
JS-01 L73: placeholder should be "notes"
TA-02: Needs acceptance test (not sure if it has)

Inventory.jsx
JS-06 L40-50: Avoid using lodash/underscore functions if possible?
DE-05: May not need so much comments

**Comment by huimichael** [comment]
DispenseInventory.jsx
- Should the fields for 'medication' and 'name' be wrapped in <From.Group/>?
- Should change the min value for quantity when dispensing to 1 (L67)
- Not allow dispensing if dispense quantity is > than current quantity

Inventory.jsx
- Design-03: L88 Category Tags filter is not being used
- Design-07: Code is hard to read at times due to excessive comments

**Comment by darneii** [comment]
DispenseInventory.jsx

    JS-01 L73: Should be "notes" instead of "Notes"

Inventory.jsx

    JS-01 L94: Should be "listContainer" instead of "listcontainer"

**Comment by acatarinaoaraujo** [comment]
DispenseInventory.jsx
* ESLINT-01 L34: Fix Eslint warning about type in class name.
* Possibly allow users to dispense multiple medicines. 
* 
Inventory.jsx
* ESLINT-01 L38, 41, 86, 87, 94: Rename class names in order to fix eslint warnings.
* TA-01: Add units that has been added to the Inventory page and collection to the test.
* Possibly link same medicines but with different lot numbers together.

**Comment by JasonKaneshiro** [comment]
DispenseInventory.jsx

JS-01 L73: placeholder should be "notes"

Inventory.jsx

DE-05 L10-54: Alot of unnecessary comments that can be summed to be more readable.
