### ISSUE TITLE
Review: UserItemAdmin, ListUserAdmin

### ISSUE THREAD

**Issue by ruizaj** [Runtime-Terrorz/HOME-Project-v2#53]
## Overview

The focus for this code review will be centered around the UserItemAdmin and
ListUserAdmin page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-53

## Files to review

* [UserItemAdmin.jsx](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/components/UserItemAdmin.jsx)
* [ListUserAdmin.jsx](https://github.com/Runtime-Terrorz/HOME-Project-v2/blob/main/app/imports/ui/pages/ListUserAdmin.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Day, Month Day Time

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ruizaj** [comment]
ListUserAdmin.jsx
- DE-06 L17-18: Space between First Name and Last Name
UserItemAdmin.jsx
- DE-01 L25-75: Similar code that can perhaps be refractored
- DE-06: Add more comments to componenets for readability

**Comment by huimichael** [comment]
ListUserAdmin.jsx
- L33: Perhaps add error check to prevent duplicate emails when defining
- Can add comments for L27 and L50 to explain the difference because it seems like they both are doing the same thing

**Comment by tonylong1314520** [comment]
UserItemAdmin.jsx
- L24-74 DE-06: Could add comments explaining the code
ListUserAdmin.jsx
- L65-70: Seems like it does not take into account for the super admin account?

**Comment by micahima** [comment]
UserItemAdmin.jsx
	* DE-01 L37, 60: removeItMethod SWAL not need for handleOnChange
	* DE-06 L26, 76: Comment code
ListUserAdmin.jsx
	* DE-06 L17,18: Missing a space between "First Name" and "Last Name"

**Comment by skimura1** [comment]
UserItemAdmin:
DE-07, L28-33, L51-56: Ensure code is DRY. Initiate the variables before L27. Do not need to reinitialize the collectionName.
JS-01: Name constructs appropriately. Can use “adminCollection” and “profileCollection” instead
Don’t show 2 swal alerts in a row

ListUserAdmin:
Missing super admin role?

**Comment by acatarinaoaraujo** [comment]
UserItemAdmin.jsx
 L5, 9: ESLINT-01: Change the order of the imports.
L27, 50: ESLINT-01: Change to be “===“, instead of “==“ and fix current file alignment. 
ListUserAdmin.jsx 
TEST-ACCEPTANCE-01: Create acceptance test for the page.
 L13, 17, 18: Replace List Profiles with Manage Accounts or something else, and give a space in FirstName and LastName.

**Comment by darneii** [comment]
ListUserAdmin.jsx

    TA-01: Need acceptance test

UserItemAdmin.jsx

    L27, 50 ES-01: Should be two = instead of three.
